
---
name: Go

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v ./...
      - name: Bump version and push tag
        id: bumpVersion
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          REPO_OWNER: jeveleth
          RELEASE_BRANCHES: main
      - name: Show new tag
        run: echo "new tag is ${{ steps.bumpVersion.outputs.new_tag }}"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
